### ISSUE TITLE
Hint Reveal: she's purity Achievements

### ISSUE THREAD

**Issue by ReiFan49** [osu-datenshi/docs#1]
- Poisonous Cloud
  * Difficulty: ★★★★★★
  * Mode; Taiko
  * Requirement:
    - Clear [Oni Difficulty](https://osu.ppy.sh/beatmaps/2537487) with 1,650 combo.
    - Mods: No difficulty reduction. (EM, NF, HT are Not Good)
- SGTBH
  * Difficulty: ★★★★★★★★★
  * Mode; Taiko
  * Requirement:
    - Clear [Ura Oni Difficulty](https://osu.ppy.sh/beatmaps/2570248) with 2,300 combo.
    - Mods: No difficulty reduction. (EM, NF, HT are Not Good)
- Deluxe Bomb
  * Difficulty: ★★★★★★★
  * Mode; Catch the Beat
  * Requirement:
    - Clear [Overdose 2013 Difficulty](https://osu.ppy.sh/beatmaps/2537488) or [Overdose Normalized Difficulty](https://osu.ppy.sh/beatmaps/2559918).
    - Have less than 10 misses.
    - Mods: No difficulty reduction. (EM, NF, HT are Not Good)
- Abandoned Doll
  * Difficulty: ★★★★★★★★★★
  * Mode; Catch the Beat
  * Requirement:
    - Clear [Overdose 2020 Difficulty](https://osu.ppy.sh/beatmaps/2570249).
    - Have less than 15 misses.
    - Mods: No difficulty reduction. (EM, NF, HT are Not Good)
  * *not even ExGon at that time can pass this sub 15 misses*.
- Bombed so Hard
  * Difficulty: ★
  * Mode: Catch the Beat
  * Requirement:
    - Clear any difficulty that is specified under Deluxe Bomb and Abandoned Doll achievement.
    - **Have at least 100 misses.**
  * *Masochism at its finest.*

**Comment by troke12** [comment]
Added
